# Site settings
title: My external brain
url: "https://myplmy.github.io"
baseurl: ""
description: >
    pain-man's notes

# My information
email: 
author: myplmy
profile: 
twitter_username: 
github_username: myplmy
comment-support: 

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
giscus:
  repo: myplmy/myplmy.github.io
  repo_id: R_kgDOKEWo-Q
  category: General
  category_id: DIC_kwDOKEWo-c4CYZ6s

# https://giscus.app/ko#category 에서 참고하여 작성하자

google_analytics:
  ua: SAMPLE-VALUE
  encrypted_ua: THIS-IS-SAMPLE-VALUE

google_adsense:
  client: SAMPLE-VALUE

blame: "https://github.com/myplmy/myplmy.github.io/blame/master/_wiki"
edit: "https://github.com/myplmy/myplmy.github.io/edit/master/_wiki"
issue: "https://github.com/myplmy/myplmy.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
